### ISSUE TITLE
geom_violin() ? 

### ISSUE THREAD

**Issue by allisonhorst** [allisonhorst/allison-sam#1]
Hey Sam, looking at the graph and wondering if we should use geom_jitter() instead. 

https://github.com/allisonhorst/allison-sam/blob/92c003329e79bee52117a2eee69b57b644373d81/git-demo.Rmd#L17

**Comment by samanthacsik** [comment]
Hey @allisonhorst I think you're right, `geom_jitter()` would be so much better here. I'll make those updates.
